# Generated by Django 3.2.9 on 2021-11-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.CharField(max_length=250, verbose_name='Почта')),
                ('seat_id', models.TextField(verbose_name='Место')),
                ('date', models.DateTimeField(verbose_name='Дата брони')),
            ],
            options={
                'verbose_name': 'комната',
                'verbose_name_plural': 'комнаты',
            },
        ),
    ]
